// Code generated by goctl. DO NOT EDIT.
package types

type AddSongRequest struct {
	Group string `json:"group"` // Имя группы
	Song  string `json:"song"`  // Название песни
}

type SongActionResponse struct {
	Message string `json:"message"` // Результат операции
}

type SongFilterRequest struct {
	Group       string `form:"group"`        // Фильтрация по имени группы
	Song        string `form:"song"`         // Фильтрация по названию песни
	Page        int64  `form:"page"`         // Номер страницы
	Limit       int64  `form:"limit"`        // Размер страницы
	ReleaseDate string `form:"release_date"` //
}

type SongListResponse struct {
	Songs []Song `json:"songs"` // Список песен
	Total int64  `json:"total"` // Общее количество записей
}

type SongVersesRequest struct {
	Song_id     int64 `form:"song_id"` // ID песни
	VerseNumber int   `json:"verse_number"`
}

type SongVersesResponse struct {
	Verses []SongVerse `json:"verses"` // Куплеты
}

type Song struct {
	Id          int64  `json:"id"`          // Уникальный идентификатор
	Group       string `json:"group"`       // Имя группы
	Song        string `json:"song"`        // Название песни
	ReleaseDate string `json:"releaseDate"` // Дата релиза
	Link        string `json:"link"`        // Ссылка на источник
}

type SongVerse struct {
	Verse_number int64  `json:"verse_number"` // Номер куплета
	Verse_text   string `json:"verse_text"`   // Текст куплета
}
