{
  "swagger": "2.0",
  "info:
  title: Music Library API
  version: "1.0"
  description: API for managing a music library, including CRUD operations and fetching song details.
servers:
  - url: http://127.0.0.1:8080
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/songs": {
      "get": {
        "summary": "Get a list of songs",
        "operationId": "ListSongsHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongListResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "group",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "song",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "tags": [
          "musicLibrary-api"
        ],
        "consumes": [
          "multipart/form-data"
        ]
      }
    },
    "/songs/create": {
      "post": {
        "summary": "Add a new song",
        "operationId": "AddSongHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongActionResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddSongRequest"
            }
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      }
    },
    "/songs/delete/{id}": {
      "delete": {
        "summary": "Delete a song",
        "operationId": "DeleteSongHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongActionResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      }
    },
    "/songs/update/{id}": {
      "put": {
        "summary": "Update song data",
        "operationId": "UpdateSongHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongActionResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SongUpdate"
            }
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      }
    },
    "/songs/verse/{id}/{verse_id}": {
      "get": {
        "summary": "Get song verses text",
        "operationId": "GetSongVersesHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongVersesResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "verse_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      }
    }
  },
  "definitions": {
    "AddSongRequest": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        }
      },
      "title": "AddSongRequest",
      "required": [
        "group",
        "song"
      ]
    },
    "Song": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        },
        "releaseDate": {
          "type": "string"
        },
        "link": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "title": "Song",
      "required": [
        "id",
        "group",
        "song",
        "releaseDate",
        "link",
        "text"
      ]
    },
    "SongActionResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      },
      "title": "SongActionResponse",
      "required": [
        "message"
      ]
    },
    "SongDeleteRequest": {
      "type": "object",
      "properties": {
        "song_id": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "SongDeleteRequest",
      "required": [
        "song_id"
      ]
    },
    "SongFilterRequest": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        },
        "page": {
          "type": "integer",
          "format": "int64"
        },
        "limit": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "SongFilterRequest",
      "required": [
        "group",
        "song",
        "page",
        "limit"
      ]
    },
    "SongListResponse": {
      "type": "object",
      "properties": {
        "songs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Song"
          }
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "SongListResponse",
      "required": [
        "songs",
        "total"
      ]
    },
    "SongUpdate": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        },
        "releaseDate": {
          "type": "string"
        },
        "link": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "title": "SongUpdate",
      "required": [
        "group",
        "song",
        "releaseDate",
        "link",
        "text"
      ]
    },
    "SongVersesRequest": {
      "type": "object",
      "properties": {
        "song_id": {
          "type": "integer",
          "format": "int64"
        },
        "verse_number": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "SongVersesRequest",
      "required": [
        "song_id",
        "verse_number"
      ]
    },
    "SongVersesResponse": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "group": {
          "type": "string"
        },
        "song": {
          "type": "string"
        },
        "releaseDate": {
          "type": "string"
        },
        "link": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "title": "SongVersesResponse",
      "required": [
        "id",
        "group",
        "song",
        "releaseDate",
        "link",
        "text"
      ]
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "description": "Enter JWT Bearer token **_only_**",
      "name": "Authorization",
      "in": "header"
    }
  }
}
