{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/songs": {
      "get": {
        "summary": "Получить список песен",
        "operationId": "ListSongsHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongListResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "group",
            "description": " Фильтрация по имени группы",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "song",
            "description": " Фильтрация по названию песни",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "page",
            "description": " Номер страницы",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "limit",
            "description": " Размер страницы",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "release_date",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "musicLibrary-api"
        ],
        "consumes": [
          "multipart/form-data"
        ]
      },
      "post": {
        "summary": "Добавить новую песню",
        "operationId": "AddSongHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongActionResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "description": " Запрос для добавления песни",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddSongRequest"
            }
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      }
    },
    "/songs/{id}": {
      "delete": {
        "summary": "Удалить песню",
        "operationId": "DeleteSongHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongActionResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      },
      "put": {
        "summary": "Изменить данные песни",
        "operationId": "UpdateSongHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongActionResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "description": " Модель песни",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Song"
            }
          }
        ],
        "tags": [
          "musicLibrary-api"
        ]
      }
    },
    "/songs/{id}/verses": {
      "get": {
        "summary": "Получить текст куплетов песни",
        "operationId": "GetSongVersesHandler",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/SongVersesResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "song_id",
            "description": " ID песни",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "verse_number",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "tags": [
          "musicLibrary-api"
        ],
        "consumes": [
          "multipart/form-data"
        ]
      }
    }
  },
  "definitions": {
    "AddSongRequest": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string",
          "description": " Имя группы"
        },
        "song": {
          "type": "string",
          "description": " Название песни"
        }
      },
      "title": "AddSongRequest",
      "required": [
        "group",
        "song"
      ]
    },
    "Song": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "description": " Уникальный идентификатор"
        },
        "group": {
          "type": "string",
          "description": " Имя группы"
        },
        "song": {
          "type": "string",
          "description": " Название песни"
        },
        "releaseDate": {
          "type": "string",
          "description": " Дата релиза"
        },
        "link": {
          "type": "string",
          "description": " Ссылка на источник"
        }
      },
      "title": "Song",
      "required": [
        "id",
        "group",
        "song",
        "releaseDate",
        "link"
      ]
    },
    "SongActionResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "description": " Результат операции"
        }
      },
      "title": "SongActionResponse",
      "required": [
        "message"
      ]
    },
    "SongFilterRequest": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string",
          "description": " Фильтрация по имени группы"
        },
        "song": {
          "type": "string",
          "description": " Фильтрация по названию песни"
        },
        "page": {
          "type": "integer",
          "format": "int64",
          "description": " Номер страницы"
        },
        "limit": {
          "type": "integer",
          "format": "int64",
          "description": " Размер страницы"
        },
        "release_date": {
          "type": "string"
        }
      },
      "title": "SongFilterRequest",
      "required": [
        "group",
        "song",
        "page",
        "limit",
        "release_date"
      ]
    },
    "SongListResponse": {
      "type": "object",
      "properties": {
        "songs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Song"
          },
          "description": " Список песен"
        },
        "total": {
          "type": "integer",
          "format": "int64",
          "description": " Общее количество записей"
        }
      },
      "title": "SongListResponse",
      "required": [
        "songs",
        "total"
      ]
    },
    "SongVerse": {
      "type": "object",
      "properties": {
        "verse_number": {
          "type": "integer",
          "format": "int64",
          "description": " Номер куплета"
        },
        "verse_text": {
          "type": "string",
          "description": " Текст куплета"
        }
      },
      "title": "SongVerse",
      "required": [
        "verse_number",
        "verse_text"
      ]
    },
    "SongVersesRequest": {
      "type": "object",
      "properties": {
        "song_id": {
          "type": "integer",
          "format": "int64",
          "description": " ID песни"
        },
        "verse_number": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "SongVersesRequest",
      "required": [
        "song_id",
        "verse_number"
      ]
    },
    "SongVersesResponse": {
      "type": "object",
      "properties": {
        "verses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SongVerse"
          },
          "description": " Куплеты"
        }
      },
      "title": "SongVersesResponse",
      "required": [
        "verses"
      ]
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "description": "Enter JWT Bearer token **_only_**",
      "name": "Authorization",
      "in": "header"
    }
  }
}
